version: '3.8'

x-environment-defaults: &environment-defaults
  DEBUG: "False"
  DB_NAME: "prediction"
  DB_USER: "prediction"
  DB_PASSWORD: "prediction"
  DB_HOST: "postgres-db"
  DB_PORT: 5432

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - .env:/syn/.env.docker
      - static_volume:/app/static/
    networks:
      - prediction-network
    expose:
      - 8000

    depends_on:
      - postgres-db
    environment:
      <<: *environment-defaults


    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application




  redis:
      image: redis:latest
      ports:
        - "6379:6379"
      networks:
        - prediction-network



  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: prediction
      POSTGRES_USER: prediction
      POSTGRES_PASSWORD: prediction
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - prediction-network


  nginx:
      image: nginx:latest
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - static_volume:/static
      ports:
        - "80:80"
      networks:
        - prediction-network
      depends_on:
        - web


volumes:
  pg_data:
  static_volume:

networks:
    prediction-network:
      driver: bridge