version: '3.8'




services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - .env:/tld/.env.docker
      - static_volume:/app/static/
    networks:
      - prediction-network
    expose:
      - 8000
    environment:
      <<: *environment-defaults


    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application




  redis:
      image: redis:latest
      ports:
        - "6379:6379"
      networks:
        - prediction-network





  nginx:
      image: nginx:latest
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - static_volume:/static
      ports:
        - "80:80"
      networks:
        - prediction-network
      depends_on:
        - web


volumes:
  pg_data:
  static_volume:

networks:
    prediction-network:
    driver: bridge