# Generated by Django 5.1.2 on 2024-10-13 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_salesman"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesmanAdditionally",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "salesman",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.salesman",
                    ),
                ),
            ],
        ),
    ]
