# Generated by Django 5.1.2 on 2024-10-13 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_salesmanadditionally"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesman",
            options={
                "verbose_name": "Продавец",
                "verbose_name_plural": "Продавец",
            },
        ),
        migrations.AlterModelOptions(
            name="salesmanadditionally",
            options={
                "verbose_name": "Продавец",
                "verbose_name_plural": "Продавец",
            },
        ),
        migrations.AlterField(
            model_name="salesman",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="salesman",
            name="products",
            field=models.ManyToManyField(
                to="product.product",
                verbose_name="Внешний ключ на таблицу Product",
            ),
        ),
        migrations.AlterField(
            model_name="salesmanadditionally",
            name="description",
            field=models.TextField(verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="salesmanadditionally",
            name="salesman",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="product.salesman",
                verbose_name="Внешний ключ на таблицу Salesman",
            ),
        ),
    ]
