# Generated by Django 5.1.2 on 2024-10-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_salesman_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesmanadditionally",
            options={
                "verbose_name": "доп описание к продавцу",
                "verbose_name_plural": "доп описание к продавцам",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Имя"
            ),
        ),
    ]
