# Generated by Django 5.1.2 on 2024-10-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_remove_salesmanadditionally_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesmanadditionally",
            name="description",
            field=models.TextField(default=1, verbose_name="описание"),
            preserve_default=False,
        ),
    ]
