# Generated by Django 5.1.2 on 2024-10-13 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_salesmanadditionally_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_category",
                to="product.category",
                verbose_name="Внешний ключ на таблицу Category",
            ),
        ),
    ]
